version: 2.1
orbs:
  node: circleci/node@5
  evals: circleci/evals@2.0
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default
            --reporters=jest-junit
      - store_test_results:
          path: ./test-results/
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found github actions config
          command: ":"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json 
          results: test_results.xml
workflows:
  build-and-test:
    jobs:
      - test-node:
          context: []
  #test-eval-workflow:
  #  jobs:
   #   - evals-test-assertions-job
